// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDssy_ZpEvaF7ofeeCDySqonZ_FxV0dUHs',
    appId: '1:884481263866:web:692878f03458d7a1826143',
    messagingSenderId: '884481263866',
    projectId: 'happycam-9abb5',
    authDomain: 'happycam-9abb5.firebaseapp.com',
    storageBucket: 'happycam-9abb5.firebasestorage.app',
    measurementId: 'G-LDBX461JSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOynBfbS-yyjQ-_NBkErWYTBzneErpSWs',
    appId: '1:884481263866:android:b4489e86063dc19f826143',
    messagingSenderId: '884481263866',
    projectId: 'happycam-9abb5',
    storageBucket: 'happycam-9abb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwhczULVdCwj7cy8kueg2Nucd5sLld8Vc',
    appId: '1:884481263866:ios:52a00e044fb390b4826143',
    messagingSenderId: '884481263866',
    projectId: 'happycam-9abb5',
    storageBucket: 'happycam-9abb5.firebasestorage.app',
    iosBundleId: 'com.example.happyCam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwhczULVdCwj7cy8kueg2Nucd5sLld8Vc',
    appId: '1:884481263866:ios:52a00e044fb390b4826143',
    messagingSenderId: '884481263866',
    projectId: 'happycam-9abb5',
    storageBucket: 'happycam-9abb5.firebasestorage.app',
    iosBundleId: 'com.example.happyCam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDssy_ZpEvaF7ofeeCDySqonZ_FxV0dUHs',
    appId: '1:884481263866:web:77e6c128204fd919826143',
    messagingSenderId: '884481263866',
    projectId: 'happycam-9abb5',
    authDomain: 'happycam-9abb5.firebaseapp.com',
    storageBucket: 'happycam-9abb5.firebasestorage.app',
    measurementId: 'G-RCPD98ME7T',
  );
}
